trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x86|x64|ARM'
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

steps:
- script: |
    echo "Installing NuGet tool..."
    nuget restore $(solution)
    echo "Building solution..."
    msbuild $(solution) /p:Configuration=$(buildConfiguration) /p:Platform=$(buildPlatform) /p:AppxPackageDir=$(appxPackageDir) /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload
    echo "Running tests"
    # Add your test commands here